[package]
name = "advent-of-code"
version = "0.1.1"
authors = ["Erich Healy <ErichRHealy@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
itertools = "*"
