[package]
name = "advent-of-code"
version = "0.1.1"
authors = ["Erich Healy <ErichRHealy@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.10.5"
regex = "1.7.0"
